### ISSUE TITLE
ArgoCD tries to remove AKS added matchExpression control-plane

### ISSUE THREAD

**Issue by megian** [projectsyn/component-cert-manager#19]
AKS is adding an extra matchExpression to ValidatingWebhookConfiguration.

https://docs.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces

> To protect the stability of the system and prevent custom admission controllers from impacting internal services in the kube-system, namespace AKS has an Admissions Enforcer, which automatically excludes kube-system and AKS internal namespaces. This service ensures the custom admission controllers don't affect the services running in kube-system.

The cert-manager helm chart object is patched continuously by the AKS K8s Admissions Enforcer.
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cert-manager-webhook
webhooks:
  - name: webhook.cert-manager.io
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
```
Currently the helm chart does not support configuring it https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml#L27 statically for AKS.

## Steps to Reproduce the Problem

  1. Take any AKS cluster
  1. Configure the component cert-manager v2.0.0
  1. Check ArgoCD for unsychronized items 

## Actual Behavior
ArgoCD is continuously removing the cert-manager application matchExpression. The AKS Admissions Enforcer is continuously adding it.

## Expected Behavior
The additional matchExpression can be configured.
