### ISSUE TITLE
Allow to configure secrets required for DNS01 solvers

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/component-cert-manager#24]
## Context
Most if not all DNS01 solvers require some sort of credentials. Those credentials are supposed to be put into a Kubernetes Secret which then gets referenced in the solvers section of the (Cluster)Issuer. In order to do so, the component should allow to confiugre a list of arbitrary Secretes which then can be referenced in solvers.

```yaml
cert-manager:
  secrets:
    acmedns:
      stringData:
        acmedns.json: ?{vaultkv:${cluster:tenant}/${cluster:name}/acmedns}

  solvers:
    dns01:
      acmeDNS:
        accountSecretRef:
          name: acmedns
            key: acmedns.json
          host: auth.example.com
```

## Alternatives
Allow the credentials to be configured as part of the solver data structure and convert it to a Secret within Jsonnet.
This favours the users perspective (simpler to configure). From a maintainers prespective, this is less favourlable as we would have to cover each and every solver (each does things a bit different) and we would have to actively support new ones.
